name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests..."

      - name: Install Google Cloud CLI
        run: |
          echo "Installing Google Cloud CLI..."
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-432.0.0-linux-x86_64.tar.gz
          tar -xf google-cloud-cli-432.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh -q
          export PATH=$PATH:$(pwd)/google-cloud-sdk/bin
          gcloud --version

      - name: Create GCP credentials file from Base64
        run: |
          echo "Creating GCP credentials file from Base64..."
          echo "${{ secrets.GCP_CREDENTIALS}}" | base64 --decode > /tmp/gcp-key.json

      - name: Verify GCP credentials file exists
        run: |
          cat /tmp/gcp-key.json
          
      - name: Configure GCP project
        run: |
          echo "Configuring GCP project..."
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project lsa-data-425320

      - name: Deploy to GCP
        run: |
          echo "Deploying to GCP..."
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash -s" < install.sh
