name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install Google Cloud CLI
        run: |
          echo "Installing Google Cloud CLI..."
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-432.0.0-linux-x86_64.tar.gz
          tar -xf google-cloud-cli-432.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh -q
          export PATH=$PATH:$(pwd)/google-cloud-sdk/bin
          gcloud --version

      - name: Create GCP credentials file from Base64
        run: |
          echo "Creating GCP credentials file from Base64..."
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > /tmp/gcp-key.json

      - name: Authenticate to Google Cloud
        run: |
          echo "Authenticating to Google Cloud..."
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project lsa-data-425320

      - name: Copy install.sh to GCP server
        run: |
          echo "Copying install.sh to GCP server..."
          gcloud compute scp install.sh gcp-web-server:/tmp/install.sh --zone "us-central1-c"

      - name: Run install.sh on GCP server
        run: |
          echo "Running install.sh on GCP server..."
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash /tmp/install.sh"

      - name: Check Apache status
        run: |
          echo "Checking Apache status..."
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "sudo systemctl status apache2"

      - name: Test HTTP request to Apache server
        run: |
          echo "Testing HTTP request..."
          curl http://34.172.53.61
