name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GCP
        run: |
          echo "Deploying to GCP..."
          echo "${{ secrets.GCP_CREDENTIALS }}" | gcloud auth activate-service-account --key-file=/dev/stdin
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash -s" < install.sh
