name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GCP with sudo
        run: |
          echo "Deploying to GCP..."
          sudo gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          sudo gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash -s" < install.sh
