name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GCP credentials file
        run: |
          echo "Creating GCP credentials file..."
          printf '%s' "${{ secrets.GCP_CREDENTIALS }}" > /tmp/gcp-key.json

      - name: Verify GCP credentials file exists
        run: |
          cat /tmp/gcp-key.json

      - name: Deploy to GCP
        run: |
          echo "Deploying to GCP..."
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash -s" < install.sh
