name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests..." 

      - name: Install Google Cloud CLI  # התקנת CLI תוך ניהול מפתח ציבורי בצורה נכונה
        run: |
          echo "Installing Google Cloud CLI..."
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          sudo mkdir -p /usr/share/keyrings
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Deploy to GCP
        run: |
          echo "Deploying to GCP..."
          gcloud auth activate-service-account --key-file ${{ secrets.GCP_CREDENTIALS }}
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash -s" < install.sh 
