name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # שימוש בגירסה v4 שמותאמת ל-Node.js 20

      - name: Run tests
        run: echo "Running tests..." 

      - name: Install Google Cloud SDK
        run: |
          echo "Installing Google Cloud SDK..."
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y google-cloud-sdk

      - name: Deploy to GCP
        run: |
          echo "Deploying to GCP..."
          gcloud auth activate-service-account --key-file ${{ secrets.GCP_CREDENTIALS }}
          gcloud compute ssh gcp-web-server --zone "us-central1-c" --command "bash -s" < install.sh 
